// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfmmvddhdzeimtiebrvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmbW12ZGRoZHplaW10aWVicnZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTkzNTIsImV4cCI6MjA3MzY3NTM1Mn0.WqAYWwzlX9vz4JsClS4FSMpZzVabHV3H-2AhtPUoioo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});